### ISSUE TITLE
Testing using queues : RuntimeError KeyError('ZRRnmTAGxe')

### ISSUE THREAD

**Issue by briva** [potatolondon/djangae#845]
Hello.

Im currently trying using queues appengine with djangae.

Using this sample with django adaptation.

`@csrf_exempt
def enqueue(request):
    amount = int(request.POST['amount'])

    queue = taskqueue.Queue(name='default')

    task = taskqueue.Task(
        url='/update_counter/',
        target='worker',
        params={'amount': amount})

    rpc = queue.add_async(task)

    # Wait for the rpc to complete and return the queued task.
    task = rpc.get_result()

    return HttpResponse('Task '+str(task.name)+' enqueued, ETA '+str(task.eta))`

But when the task is created, I got this : 

> Exception while handling service_name: "modules"
> method: "GetHostname"
> request: "\n\006worker"
> request_id: "bCOzNWmQRZ"

> RuntimeError at /enqueue/
> KeyError('ZRRnmTAGxe',)
> Request Method:	POST
> Request URL:	http://0.0.0.0:8000/enqueue/
> Django Version:	1.10.5
> Exception Type:	RuntimeError
> Exception Value:	
> KeyError('ZRRnmTAGxe',)
> Exception Location:	/Users/2brivael3/Documents/google-cloud-sdk/platform/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py in _MakeRealSyncCall, line 267
> Python Executable:	/Users/2brivael3/Desktop/project_global/project_core/venv/bin/python
> Python Version:	2.7.10
> Python Path:	
> ['lib',
>  '/Users/2brivael3/Desktop/project_core',
>  '/Users/2brivael3/Desktop/project_core/lib/djangae/lib',
>  '/Users/2brivael3/Desktop/project_core/lib',
>  '/Users/2brivael3/Documents/google-cloud-sdk/platform/google_appengine',
>  '/Users/2brivael3/Documents/google-cloud-sdk/platform/google_appengine',
>  '/Users/2brivael3/Desktop/project_global/project_core/venv/lib/python2.7',
>  '/Users/2brivael3/Desktop/project_global/project_core/venv/lib/python2.7/lib-dynload',
>  '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
>  '/Users/2brivael3/Documents/google-cloud-sdk/platform/google_appengine/lib/MySQLdb-1.2.5',
>  '/Users/2brivael3/Documents/google-cloud-sdk/platform/google_appengine/lib/ssl-2.7.11',
>  '/Users/2brivael3/Documents/google-cloud-sdk/platform/google_appengine/lib/grpcio-1.0.0',
>  '/Users/2brivael3/Documents/google-cloud-sdk/platform/google_appengine/lib/protorpc-1.0',
>  '/Users/2brivael3/Documents/google-cloud-sdk/platform/google_appengine/lib/pytz-2016.4',
>  '/Users/2brivael3/Documents/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3',
>  '/Users/2brivael3/Documents/google-cloud-sdk/platform/google_appengine/lib/webob-1.1.1',
>  '/Users/2brivael3/Documents/google-cloud-sdk/platform/google_appengine/lib/werkzeug-0.11.10',
>  '/Users/2brivael3/Documents/google-cloud-sdk/platform/google_appengine/lib/yaml-3.10']

**Comment by davidwtbuxton** [comment]
I think this is the [same KeyError bug I'm running into trying to use MapReduce][1].

Have you tried deploying this code to App Engine? I think this is a bug with the local SDK, so may work in the live environment.

Have you tried using the less-flexible but simpler [deferred API?][2] That works reliably for local development using Djangae. N.B. Djangae includes a deferred handler view, use that instead of the deferred builtin handler. 


[1]: https://github.com/potatolondon/search/issues/51
[2]: https://cloud.google.com/appengine/articles/deferred

**Comment by briva** [comment]
I fixed my pb to use : dev_appserver.py app.yaml worker.yaml --admin_port=9000 --port=8000
Instead of : ./manage.py runserver

But now I have another pb :/

> ImproperlyConfigured: Requested setting ALLAUTH_SETTING_GETTER, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
> INFO     2017-02-21 00:42:50,610 module.py:806] worker: "POST /service/email/ HTTP/1.1" 500 -

**Comment by davidwtbuxton** [comment]
That error suggests you are missing logic to setup the Python environment. What is the script handler in app.yaml for the request? What setup is done in that script handler?

Important thing is to check whether the script handler for `/service/email/` is doing the necessary setup of the environment.

**Comment by briva** [comment]
My app.yaml :

```
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- remote_api: on

inbound_services:
- warmup

handlers:

- url: /_ah/(mapreduce|queue|warmup|start|stop).*
  script: core.wsgi.application
  login: admin

- url: /_ah/internalupload.*
  script: core.wsgi.application
  secure: always

- url: /static/admin/
  static_dir: lib/django/contrib/admin/static/admin/
  secure: always

- url: /static/rest_framework/
  static_dir: lib/rest_framework/static/rest_framework
  secure: always

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: core.wsgi.application
  secure: always
  login: admin

- url: /api/private.*
  script: core.wsgi.application
  secure: always
  login: admin

- url: /static/debug_toolbar/
  static_dir: lib/debug_toolbar/static/debug_toolbar

- url: /.*
  script: core.wsgi.application
  secure: never

libraries:
- name: MySQLdb
  version: "latest"
- name: ssl
  version: 2.7.11

skip_files:
    - manage.py
    - README.md
    - install_deps
    - requirements.txt
    - sitepackages/google_appengine*
    - \.storage.*
    - \.git
    - (.*)\.pyc
```

My worker.yaml :

```
runtime: python27
api_version: 1
threadsafe: true
module: worker

handlers:
- url: /.*
  script: core.views
  login: admin
```
